-- DELETE A CHILD USER FROM THE DATABASE USING FUNCTION
CREATE OR REPLACE FUNCTION DELETE_CHILD (RECEIVED_C_ID VARCHAR2)
    RETURN VARCHAR2
    IS
    USER_NOT_DELETED EXCEPTION;
    CNT INTEGER;
    E VARCHAR2(100);
BEGIN
    SELECT COUNT(*) INTO CNT FROM CHILD
    WHERE C_ID = RECEIVED_C_ID;

    IF CNT = 0
    THEN RAISE USER_NOT_DELETED;
    END IF;

    -- FIND EMAIL TO DELETE FROM LOGIN TABLE
    SELECT EMAIL INTO E FROM CHILD
    WHERE C_ID = RECEIVED_C_ID;

    -- DELETE FROM PARENT_HAS_CHILD
    DELETE FROM PARENT_HAS_CHILD
    WHERE C_ID = RECEIVED_C_ID;
    -- DELETE FROM CONSULTS
    DELETE FROM CONSULTS
    WHERE C_ID = RECEIVED_C_ID;
    --DELETE FROM SUGGESTS
    DELETE FROM SUGGESTS
    WHERE C_ID = RECEIVED_C_ID;
    -- DELETE FROM BOOKS
    DELETE FROM BOOKS
    WHERE C_ID = RECEIVED_C_ID;
    -- DELETE FROM ENROLLS
    DELETE FROM ENROLLS
    WHERE C_ID = RECEIVED_C_ID;
    -- DELETE FROM CHILD_HAS_DISORDER
    DELETE FROM CHILD_HAS_DISORDER
    WHERE C_ID = RECEIVED_C_ID;
    -- DELETE FROM CHILD
    DELETE FROM CHILD
    WHERE C_ID = RECEIVED_C_ID;
    -- DELETE FROM LOGIN
    DELETE FROM LOG_IN
    WHERE EMAIL = E;

    RETURN 'Child deleted successfully';

EXCEPTION
    WHEN USER_NOT_DELETED THEN
        RAISE_APPLICATION_ERROR(-20112,'USER NOT FOUND!');
    WHEN OTHERS THEN
        ROLLBACK;
        RETURN 'Error occurred during deletion';

END;
/